quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pacientes_db
quarkus.hibernate-orm.database.generation=update
quarkus.http.port=8081
quarkus.application.name=ms-pacientes

smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=hospital-system