# API Gateway Configuration
quarkus.http.port=8080

# Microservices URLs
ms.pacientes.url=http://localhost:8081
ms.atencion.url=http://localhost:8082
ms.recetas.url=http://localhost:8083
ms.farmacia.url=http://localhost:8084
ms.cobros.url=http://localhost:8085
ms.notificaciones.url=http://localhost:8086

# JWT Configuration
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=hospital-system