quarkus.http.port=8084
quarkus.application.name=ms-farmacia
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/farmacia_db
quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH:META-INF/resources/publicKey.pem}
mp.jwt.verify.issuer=clinica-system
quarkus.http.auth.proactive=false