server.port=8888
spring.application.name=config-server

# Ubicacion de los archivos de configuracion (carpeta central-config)
spring.cloud.config.server.git.uri=file:///${user.dir}/central-config
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.search-paths=config-properties
spring.cloud.config.server.git.default-label=main

# Seguridad (desarrollo)
spring.security.user.name=configuser
spring.security.user.password=configpass