quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pacientes_db
quarkus.hibernate-orm.database.generation=update
quarkus.http.port=8081
quarkus.application.name=ms-pacientes

smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_PATH:META-INF/resources/privateKey.pem}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH:META-INF/resources/publicKey.pem}
mp.jwt.verify.issuer=clinica-system
quarkus.http.auth.proactive=false

notificaciones-api/mp-rest/url=${MS_NOTIFICACIONES_URL:http://localhost:8086}

codigo.expiracion.minutos=15