spring.application.name=ms-farmacia
server.port=8084

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5435/farmacia_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Eureka
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.mensaje=MS-Farmacia funcionando