spring.application.name=ms-notificaciones
server.port=8086

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5437/notificaciones_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Eureka
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.mensaje=MS-Notificaciones funcionando