spring.application.name=ms-recetas
server.port=8083

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5434/recetas_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Eureka
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.mensaje=MS-Recetas funcionando