spring.application.name=ms-atencion
server.port=8082

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/atencion_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Eureka
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Mensaje del servicio
app.mensaje=MS-Atencion funcionando