spring.application.name=ms-pacientes
server.port=8081

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pacientes_db
spring.datasource.username=pacientes_user
spring.datasource.password=pacientes_pass

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mensaje del servicio
app.mensaje=MS-Pacientes funcionando