quarkus.http.port=8085
quarkus.application.name=ms-cobros
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/cobros_db
quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=hospital-system