quarkus.http.port=8085
quarkus.application.name=ms-cobros
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/cobros_db
quarkus.hibernate-orm.database.generation=update

# Saga outbox
saga.notificaciones.url=${SAGA_NOTIFICACIONES_URL:http://ms-notificaciones:8086/eventos/saga}
saga.atencion.url=${SAGA_ATENCION_URL:http://ms-atencion:8082/eventos/saga}

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH:META-INF/resources/publicKey.pem}
mp.jwt.verify.issuer=clinica-system
quarkus.http.auth.proactive=false