server.port=8761
spring.application.name=registry-server

# Desactivar registro propio (no se registra a si mismo)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Desactivar autenticacion basica (desarrollo)
eureka.server.enable-self-preservation=false

# Dashboard
eureka.dashboard.enabled=true
eureka.dashboard.path=/